In [112]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report

---

## Split the Data into Training and Testing Sets

### Step 1: Read the `lending_data.csv` data from the `Resources` folder into a Pandas DataFrame.

In [113]:
# Read the CSV file from the Resources folder into a Pandas DataFrame
lending_data = Path('Resources/lending_data.csv')
lending_data_df = pd.read_csv(lending_data)
# Review the DataFrame
lending_data_df.head()

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  loan_status  
0                 1       22800            0  
1                 0       13600            0  
2                 0       16100            0  
3                 1       22700            0  
4                 1       23000            0

### Step 2: Create the labels set (`y`)  from the “loan_status” column, and then create the features (`X`) DataFrame from the remaining columns.

In [114]:
# Separate the data into labels and features

# Separate the y variable, the labels
y = lending_data_df['loan_status']

# Separate the X variable, the features
X = lending_data_df.drop(columns='loan_status', axis=1)

In [115]:
# Review the y variable Series
y[:5]

0    0
1    0
2    0
3    0
4    0
Name: loan_status, dtype: int64

In [116]:
# Review the X variable DataFrame
X[:5]

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  
0                 1       22800  
1                 0       13600  
2                 0       16100  
3                 1       22700  
4                 1       23000

### Step 3: Check the balance of the labels variable (`y`) by using the `value_counts` function.

In [117]:
# Check the balance of our target values
y.value_counts()

loan_status
0    75036
1     2500
Name: count, dtype: int64

### Step 4: Split the data into training and testing datasets by using `train_test_split`.

In [118]:
# Import the train_test_learn module
from sklearn.model_selection import train_test_split

# Split the data using train_test_split
# Assign a random_state of 1 to the function
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

---

## Create a Logistic Regression Model with the Original Data

###  Step 1: Fit a logistic regression model by using the training data (`X_train` and `y_train`).

In [119]:
# Import the LogisticRegression module from SKLearn
from sklearn.linear_model import LogisticRegression

# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
classifier = LogisticRegression(random_state=1)

# Fit the model using training data
classifier.fit(X_train, y_train)

LogisticRegression(random_state=1)

### Step 2: Save the predictions on the testing data labels by using the testing feature data (`X_test`) and the fitted model.

In [120]:
# Make a prediction using the testing data
y_pred = classifier.predict(X_test)

### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [121]:
# Print the balanced_accuracy score of the model
balanced_accuracy_score(y_test, y_pred)

0.9520479254722232

In [122]:
# Generate a confusion matrix for the model
confusion_matrix(y_test, y_pred)

array([[18663,   102],
       [   56,   563]], dtype=int64)

In [123]:
# Print the classification report for model 1
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00     18765
           1       0.85      0.91      0.88       619

    accuracy                           0.99     19384
   macro avg       0.92      0.95      0.94     19384
weighted avg       0.99      0.99      0.99     19384



### Step 4: Answer the following question.

**Question:** How well does the logistic regression model predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** 

The logistic regression model demonstrates a strong predictive capability for both healthy (class 0) and high-risk (class 1) loan labels. For healthy loans, it achieves perfect precision and recall (both 1.00), indicating exceptional performance in correctly classifying these cases without false positives or negatives. For high-risk loans, the model's precision is 0.85, meaning that when it predicts a loan to be high risk, it is correct 85% of the time. Its recall is 0.91, capturing 91% of all actual high-risk loans.

However, the model underclassifies high-risk loans by 15%, which could be critical depending on the business context. For instance, the cost associated with misclassifying a high-risk loan as healthy could be substantial if that loan defaults. Thus, while the model is robust, the business implications of these misclassifications must be considered. In particular, it may be necessary to adjust the model's threshold for predicting high-risk loans or to incorporate this model's predictions into a larger decision-making framework that also considers the potential monetary risk to the company.

In summary, the logistic regression model is highly accurate overall but does exhibit a tendency to underclassify high-risk loans. The acceptability of this range would depend on the specific financial thresholds and risk appetites of the company using the model.

---

## Predict a Logistic Regression Model with Resampled Training Data

### Step 1: Use the `RandomOverSampler` module from the imbalanced-learn library to resample the data. Be sure to confirm that the labels have an equal number of data points. 

In [124]:
# Import the RandomOverSampler module form imbalanced-learn
from imblearn.over_sampling import RandomOverSampler

# Instantiate the random oversampler model
# # Assign a random_state parameter of 1 to the model
ros = RandomOverSampler(random_state=1)

# Fit the original training data to the random_oversampler model
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)

In [125]:
# Count the distinct values of the resampled labels data
y_resampled.value_counts()

loan_status
0    56271
1    56271
Name: count, dtype: int64

### Step 2: Use the `LogisticRegression` classifier and the resampled data to fit the model and make predictions.

In [126]:
# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
classifier = LogisticRegression(random_state=1)

# Fit the model using the resampled training data
classifier.fit(X_resampled, y_resampled)

# Make a prediction using the testing data
y_pred = classifier.predict(X_test)

### Step 3: Evaluate the model’s performance by doing the following:

* Calculate the accuracy score of the model.

* Generate a confusion matrix.

* Print the classification report.

In [127]:
# Print the balanced_accuracy score of the model 
balanced_accuracy_score(y_test, y_pred)

0.9936781215845847

In [128]:
# Generate a confusion matrix for the model
confusion_matrix(y_test, y_pred)

array([[18649,   116],
       [    4,   615]], dtype=int64)

In [129]:
# Print the classification report for model 2
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00     18765
           1       0.84      0.99      0.91       619

    accuracy                           0.99     19384
   macro avg       0.92      0.99      0.95     19384
weighted avg       0.99      0.99      0.99     19384



### Step 4: Answer the following question

**Question:** How well does the logistic regression model, fit with oversampled data, predict both the `0` (healthy loan) and `1` (high-risk loan) labels?

**Answer:** 

After accounting for the oversampling the results are much more balanced with the recall increasing to 99% for Class 1. The precision for class 1 has gone down by 1%. For a business sense this means that the model is likely to classify a healthy loan as high risk but will very rarely classify a high risk loan as healthy. This is a desireable tradeoff in a "better safe than sorry" scenario. The capital implications is "profit lost due to incorrect classification" versus "debt gained via default due to underclassifcation"

There is little to no change in the predictions for class 0 after utilizing the oversampling which means we maintain our high performing predictions of the majority class.

In [130]:
# Sum the total value of false negatives accross the entire data set
full_predict = classifier.predict(X)
full_confusion_matrix = confusion_matrix(y, full_predict)
full_confusion_matrix

array([[74613,   423],
       [   13,  2487]], dtype=int64)

In [131]:
predicted_risk_df = X

predicted_risk_df["Prediction"] = full_predict
predicted_risk_df["Actual"] = y
predicted_risk_df["False Negative"] = predicted_risk_df.apply(lambda x: 1 if x["Prediction"] == 0 and x["Actual"] == 1 else 0, axis=1)

predicted_risk_df.head()

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  Prediction  Actual  False Negative  
0                 1       22800           0       0               0  
1                 0       13600           0       0               0  
2                 0       16100           0       0               0  
3                 1       22700           0       0               0  
4                 1       23000           0       0               0

In [134]:
#filter for only false negatives
false_negatives_df = predicted_risk_df.loc[predicted_risk_df["False Negative"] == 1]
false_negatives_df.head()

loan_size  interest_rate  borrower_income  debt_to_income  \
75166     9900.0          7.312            49400        0.392713   
75228    13500.0          8.878            64100        0.531981   
75445    10600.0          7.631            52400        0.427481   
76266     9300.0          7.078            47200        0.364407   
76416     9400.0          7.126            47700        0.371069   

       num_of_accounts  derogatory_marks  total_debt  Prediction  Actual  \
75166                4                 0       19400           0       1   
75228                7                 1       34100           0       1   
75445                5                 1       22400           0       1   
76266                3                 0       17200           0       1   
76416                3                 0       17700           0       1   

       False Negative  
75166               1  
75228               1  
75445               1  
76266               1  
76416               1

In [135]:
# Sum the total value of false negatives accross the entire data set
false_negatives_df["loan_size"].sum()  

129500.0